### ISSUE TITLE
Does not compile as dependency?

### ISSUE THREAD

**Issue by futile** [Nilirad/bevy_prototype_lyon#89]
~~Does this project work with bevy 0.5? It seems bevy's "main"-branch is being tracked, but doing~~

```toml
[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_prototype_lyon = { git = "https://github.com/Nilirad/bevy_prototype_lyon.git", branch = "master" }
```

~~throws compilation errors inside `bevy_prototype_lyon` for me.~~

~~Edit: Current `master` commit when I tried this: 5c92ee50125e526e6af18c2ab913dd2581fdeded~~

Edit: The errors can be reproduced by leaving out the `bevy` dependency, so just running `cargo new` and adding

```toml
[dependencies]
bevy_prototype_lyon = { git = "https://github.com/Nilirad/bevy_prototype_lyon.git", branch = "master" }
```

at commit 5c92ee50125e526e6af18c2ab913dd2581fdeded already causes the `bevy_prototype_lyon` crate to not compile.

All of this is on windows btw.,  cargo & rust versions:

```
cargo 1.52.0-nightly (90691f2bf 2021-03-16)
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
```

But I also tried stable 1.51., which also failed.

```
cargo 1.51.0 (43b129a20 2021-03-16)
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

**However**, when cloning this repo (at the same commit), `cargo build` as well as `cargo check` both work.
